# Site settings
title: "On The Movement"
email: reeonce@gmail.com
description: "Moving all the time, capture it."
timezone: Asia/Hong_Kong
baseurl: ""
twitter_username: reeonce
github_username:  reeonce

# Build settings
gems: ['jekyll-paginate']
markdown: kramdown
kramdown:
  math_engine: mathjax
permalink: pretty
paginate: 5
paginate_path: "/blog/page:num/"

exclude:
  - tags
  - .tags
  - .tags1
  - Gemfile
  - Gemfile.lock
  - package.json
  - Gruntfile.js
  - bower.json
