# Site settings
title: "On Reeonce's Move"
email: reeonce@gmail.com
description: "Moving all the time, record it."
timezone: Asia/Hong_Kong
baseurl: ""
url: "https://reeonce.github.io"
twitter_username: reeonce
github_username:  reeonce

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
permalink: pretty
paginate: 5
paginate_path: "/blog/page:num/"
