# Site settings
title: "On The Movement"
email: reeonce@gmail.com
description: "Moving all the time, capture it."
timezone: Asia/Hong_Kong
baseurl: ""
twitter_username: reeonce
github_username:  reeonce

nav_items: 

- title: "Blogs"
  path: "/"

- title: "Notes"
  path: "/notes/"

- title: "Me"
  path: "/about/"

google_analytics: UA-65501306-1
disqus:
  shortname: reeoncesblog

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
permalink: pretty

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

remote_theme: reeonce/modernist.reeonce.github.io

collections:
  notes:
    output: true

exclude:
  - tags
  - .tags
  - .tags1
  - Gemfile
  - Gemfile.lock
  - package.json
  - Gruntfile.js
  - bower.json
