# Site settings
title: "Reeonce On The Move"
email: reeonce@gmail.com
description: "Moving all the time, record it."
timezone: Asia/Hong_Kong
baseurl: ""
twitter_username: reeonce
github_username:  reeonce

# Build settings
gems: ['jekyll-paginate']
markdown: kramdown
permalink: pretty
paginate: 5
paginate_path: "/blog/page:num/"

exclude:
  - tags
  - .tags
  - .tags1
  - Gemfile
  - Gemfile.lock
  - package.json
  - Gruntfile.js
  - bower.json
